### ISSUE TITLE
Add missing tags to all updates

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/website#212]
# Overview 
Updates on our websites can be tagged with the project name. Currently on the [page](https://tattle.co.in/updates/), only  two projects have tags. Go  through every update and add a project specific tag.

**Comment by Mahimahto** [comment]
could you please assign this issue to me?

**Comment by khushboo-102** [comment]
Please Assign too

**Comment by dennyabrain** [comment]
@khushboo-102 you and preeti are working on this issue https://github.com/tattle-made/website/issues/211

**Comment by dennyabrain** [comment]
@maanasb01 can you help manisha get the formatting right?

**Comment by maanasb01** [comment]
Hey @Mahimahto, there seems to be a formatting issue in your last message. Can you please go through this Github documentation on formatting syntax and fix the formatting of your previous message? You don't need to read the entire documentation, you can just refer to the parts that seem useful for current use (like Headings, Stylings, Code Blocks, etc.) and keep this documentation for later reference. 

Here is the link to the doc: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

**Comment by Mahimahto** [comment]
---

# Task: Add Project-Specific Tags to Updates in the Website

## Objective  
Ensure all updates on the website are categorized with relevant project-specific tags.

---

## Current Setup  

- **Framework:** Gatsby  
- **Updates Location:** `src/updates/` (stored as individual Markdown files).  
- **Frontmatter Fields in Markdown Files:**  
  ```yaml
  date: Date of the update  
  title: Title of the update  
  excerpt: A brief description of the update  
  url: Link to the update's source  
  tags: An array of tags (e.g., Paper, Talk)  
  ```

---

## Steps to Complete the Task  

### 1. **Understand the Existing Updates**  
   - Review each Markdown file in the `src/updates/` folder.  
   - Use the `title` and `excerpt` fields to determine the context and associated project.

### 2. **Add Project Tags**  
   - Add a project-specific tag to the `tags` field in the frontmatter.  
   - Use existing project names like `Scaling Vectors`, `PathFollower`, etc., as tags.

   #### Example:  
   **Before:**  
   ```yaml
   date: 2019-10-04  
   title: "Considerations in Archiving Content from Encrypted Messaging Apps"  
   excerpt: "Comparative Approaches to Disinformation, Berkman Klein Center, Harvard University"  
   url: "https://cyber.harvard.edu/story/2019-10/comparative-approaches-disinformation"  
   tags: [Paper, Talk]  
   ```  
   **After:**  
   ```yaml
   date: 2019-10-04  
   title: "Considerations in Archiving Content from Encrypted Messaging Apps"  
   excerpt: "Comparative Approaches to Disinformation, Berkman Klein Center, Harvard University"  
   url: "https://cyber.harvard.edu/story/2019-10/comparative-approaches-disinformation"  
   tags: [Paper, Talk, Scaling Vectors]  
   ```

### 3. **Ensure Consistency**  
   - Maintain consistency in the naming and usage of project tags.

### 4. **Automate (Optional)**  
   - Write a script to match keywords in the `title` or `excerpt` fields to project tags.  
   - Example: Use a Python script to parse Markdown files and automate tag addition.  

### 5. **Test Changes**  
   - Run the Gatsby development server with `gatsby develop`.  
   - Verify that the tags appear correctly on the website.

### 6. **Push Changes**  
   - Commit and push the changes to the Git repository after successful testing.

---

## Questions to Confirm  
1. Is the task limited to adding tags only to existing updates, or should new updates include tags as well?  
2. Should we follow a specific naming convention for project tags?  
3. Is it acceptable to automate the tagging process using a script, or should it be done manually for accuracy?  

---

## My Understanding  
I will execute this task step-by-step:  
1. Review Markdown files in `src/updates/`.  
2. Identify the project for each update.  
3. Add relevant project tags to the `tags` field.  
4. Test changes locally using `gatsby develop`.  
5. Push the changes to the repository after testing.  

Let me know if this approach is correct or if further clarification is needed.

---
